import { Listing } from './listing.model';

export const LISTINGS: Listing[] = [
  new Listing('36 Sesame Street Books', 175, 'Lake Stevens', 'All Books are in great condition all hard cover with tight bindings. There are some minor scribbles in a couple of the books.', 1, 1),
  new Listing('The Hunger Games', 5, 'The Moon', 'It\'s a book.', 1, 2),
  new Listing('bridge case', 60, 'queen anne', 'its a nice case with speerate 15 metal card holders (holds a full deck) with original scorecards', 2, 3),
  new Listing('Chelsea Claremont Clock & Barometer', 1400, 'Seattle', '1955-59 Chelsea Claremont Clock & Barometer Desk Set. This gorgeous vintage Chelsea Ship\'s Bell Clock & Barometer set has just been professionally polished and clear coated with clear marine lacquer. It comes with the original key. The chime works perfectly and strikes every half hour, one to eight bell over a four hour period. The clock keeps very good time, the dial is in mint condition and includes a switch to turn off the bells. The barometer and temperature gauge work. A true nautical desk clock set. Email with your name and phone number for reply.', 2, 4),
  new Listing('Barbie Dream House', 50, 'Lake Forest Park', 'Barbie Dream House in excellent condition. All assembly is done and ready for you to take home! Furniture and all working pieces/sounds included.', 3, 5),
  new Listing('Terra Mystica Fire and Ice Expansion - New in Shrink', 40, 'Green Lake', 'Great expansion for Terra Mystica. Received as a gift but already had a copy, and can\'t return. $40 obo.', 3, 6),
  new Listing('Free Mobile Home/Trailer', 0, 'Sequim', 'Free older mobile home. Must be able to disconnect utilities and haul off property. If interested text or call between the hours of 9 am and 7 pm (pst)', 4, 7),
  new Listing('GE Profile Double Microwave/Convection Wall Oven - Stainless Steel', 0, 'Kirkland', 'Everything in great working order, just recently removed from kitchen because we updated all our appliances. Some of the microwave interior coating is showing wear but can probably be fixed.', 4, 8),
  new Listing('Rustic Roll Top Wood Desk', 75, 'Puyallup South Hill', 'Rustic roll top wood desk. Made from a combination of solid wood and Fir Plywood. 36"L x 20"W x 41"H. built by a family member in the 50\'s. $75.00. If it is posted, it is available!!! Please respond with a day and time that you are available.', 5, 9),
  new Listing('Hammock', 125, 'University Place', 'This is a near new Pier 1 free standing hammock. The hammock cost $199.99 and the sturdy hammock stand cost $179.00. For use Inside and Outside. Comes with a bag for the hammock. It is the red one in the picture.', 5, 10),
  new Listing(' Joseph Sterling Close Contact Saddle **NEW**', 999, 'Poulsbo', 'I bought this saddle brand new, rode in it maybe 5 times and decided to keep using my Crates. It\'s been kept covered indoors and oiled. Just needs YOU to break it in! 17" seat with a medium, lifetime warranted spring steel tree. This saddle isn\'t even available in this seat size anymore, and it\'s been so exceptionally cared for, no one will know you purchased pre-owned. I will also include the saddle cover, which retailed for $50. Also brand new!', 6, 11),
  new Listing('anvil', 1250, 'snohomish', '250 pound blacksmiths anvil, still mounted on the same post it was used on, you\'re welcome to have the post also. This anvil is in excellent shape and a great addition to any collection or to use.', 6, 12),
  new Listing('2007 Lexus IS 250', 6600, 'Tacoma', 'Selling a 2007 Lexus IS 250 runs and drives doesn\'t have any mechanical issues fully loaded with leather seats power windows and locks everything works 200k + miles & clean title. If interested shoot a text or call', 7, 13),
  new Listing('2006 Ford F350 Lariat 4x4 crew cab diesel', 18500, 'Renton', 'I don\'t need help selling it. I\'m not interested in trades. I won\'t ship it to the east coast so your mechanic can look at it. No Paypal. Cash only, face to face. Don\'t call me with an offer if you haven\'t seen the truck in person. I know this sounds grumpy but if you\'ve never listed something for sale here then you wouldn\'t believe all the crap calls you get.', 7, 14),
  new Listing('Croquet Set', 15, 'University Place', 'Nice croquet set for 6 players. Great for family fun! Cost $49.99 new.', 8, 15),
  new Listing('Heavy Duty Desktop ACCO 131 Stapler', 15, 'Lakewood', 'ACCO 131 · Manual · Desktop · Heavy Duty industrial stapler includes 1 1/2 boxes of staples. This stapler will staple dozens of pages at one time.', 8, 16),
]
